"""Create tables

Revision ID: 27afb0b3f94c
Revises: 
Create Date: 2023-09-28 08:39:23.060403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27afb0b3f94c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('account_created_on', sa.DateTime(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('admin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latin_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('warnings', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('entered_on', sa.DateTime(), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], name=op.f('fk_herbs_entered_by_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entered_on', sa.DateTime(), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], name=op.f('fk_properties_entered_by_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('entered_on', sa.DateTime(), nullable=True),
    sa.Column('directions', sa.String(), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], name=op.f('fk_recipes_entered_by_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('entered_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_comments_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosage_form', sa.String(), nullable=True),
    sa.Column('dosage_description', sa.String(), nullable=True),
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_dosages_herb_id_herbs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herb_property_association',
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_herb_property_association_herb_id_herbs')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_herb_property_association_property_id_properties'))
    )
    op.create_table('herb_recipe_association',
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_herb_recipe_association_herb_id_herbs')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_herb_recipe_association_recipe_id_recipes'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('amount_type', sa.String(), nullable=True),
    sa.Column('herb_type', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('herb_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_ingredients_herb_id_herbs')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_ingredients_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_property_association',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_recipe_property_association_property_id_properties')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_property_association_recipe_id_recipes'))
    )
    op.create_table('user_saved_herbs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_user_saved_herbs_herb_id_herbs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_saved_herbs_user_id_users'))
    )
    op.create_table('user_saved_recipes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_user_saved_recipes_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_saved_recipes_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_recipes')
    op.drop_table('user_saved_herbs')
    op.drop_table('recipe_property_association')
    op.drop_table('ingredients')
    op.drop_table('herb_recipe_association')
    op.drop_table('herb_property_association')
    op.drop_table('dosages')
    op.drop_table('comments')
    op.drop_table('recipes')
    op.drop_table('properties')
    op.drop_table('herbs')
    op.drop_table('users')
    # ### end Alembic commands ###
