"""Updates to relationships and foreignkeys

Revision ID: 592e8bcc5196
Revises: 70be518165ff
Create Date: 2023-09-01 10:26:37.400285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592e8bcc5196'
down_revision = '70be518165ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_herbs_entered_by_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_herbs_entered_by_id_users'), 'users', ['entered_by_id'], ['id'])
        batch_op.drop_column('entered_by')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_properties_entered_by_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_properties_entered_by_id_users'), 'users', ['entered_by_id'], ['id'])
        batch_op.drop_column('entered_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_properties_entered_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_properties_entered_by_users', 'users', ['entered_by'], ['id'])
        batch_op.drop_column('entered_by_id')

    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_herbs_entered_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_herbs_entered_by_users', 'users', ['entered_by'], ['id'])
        batch_op.drop_column('entered_by_id')

    # ### end Alembic commands ###
