"""Updated model relationships

Revision ID: 70be518165ff
Revises: c5fc0fc5905a
Create Date: 2023-09-01 10:21:55.326095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70be518165ff'
down_revision = 'c5fc0fc5905a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_ids', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_herbs_property_ids_properties'), 'properties', ['property_ids'], ['id'])

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herb_ids', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipe_ids', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_properties_recipe_ids_recipes'), 'recipes', ['recipe_ids'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_properties_herb_ids_herbs'), 'herbs', ['herb_ids'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_properties_herb_ids_herbs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_properties_recipe_ids_recipes'), type_='foreignkey')
        batch_op.drop_column('recipe_ids')
        batch_op.drop_column('herb_ids')

    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_herbs_property_ids_properties'), type_='foreignkey')
        batch_op.drop_column('property_ids')

    # ### end Alembic commands ###
