"""Fixed User/Recipe backpopulates issue

Revision ID: a4625ffa418d
Revises: dfce93f527ba
Create Date: 2023-09-01 12:54:12.557741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4625ffa418d'
down_revision = 'dfce93f527ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_recipes_entered_by_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recipes_entered_by_id_users'), 'users', ['entered_by_id'], ['id'])
        batch_op.drop_column('entered_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_recipes_entered_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_recipes_entered_by_users', 'users', ['entered_by'], ['id'])
        batch_op.drop_column('entered_by_id')

    # ### end Alembic commands ###
