"""Added models and validations, fixed issues

Revision ID: c5fc0fc5905a
Revises: 
Create Date: 2023-08-31 16:33:07.133464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fc0fc5905a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_herbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('amount_type', sa.String(), nullable=True),
    sa.Column('herb_type', sa.String(), nullable=True),
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_recipe_herbs_herb_id_herbs')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_herbs_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_herbs')
    # ### end Alembic commands ###
