"""Added herb_property association table, imported to Herb, Property, and RecipeHerb

Revision ID: dfce93f527ba
Revises: 592e8bcc5196
Create Date: 2023-09-01 12:50:24.105201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfce93f527ba'
down_revision = '592e8bcc5196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herb_property_association',
    sa.Column('herb_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herb_id'], ['herbs.id'], name=op.f('fk_herb_property_association_herb_id_herbs')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_herb_property_association_property_id_properties'))
    )
    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_herbs_property_ids_properties', type_='foreignkey')
        batch_op.drop_column('property_ids')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_recipe_ids_recipes', type_='foreignkey')
        batch_op.drop_constraint('fk_properties_herb_ids_herbs', type_='foreignkey')
        batch_op.drop_column('recipe_ids')
        batch_op.drop_column('herb_ids')

    with op.batch_alter_table('recipe_herbs', schema=None) as batch_op:
        batch_op.drop_column('properties')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('properties', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herb_ids', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('recipe_ids', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_properties_herb_ids_herbs', 'herbs', ['herb_ids'], ['id'])
        batch_op.create_foreign_key('fk_properties_recipe_ids_recipes', 'recipes', ['recipe_ids'], ['id'])

    with op.batch_alter_table('herbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_ids', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_herbs_property_ids_properties', 'properties', ['property_ids'], ['id'])

    op.drop_table('herb_property_association')
    # ### end Alembic commands ###
