"""Fixed recipe issue in Herb model

Revision ID: e71f83323bb5
Revises: a4625ffa418d
Create Date: 2023-09-01 13:05:52.672614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71f83323bb5'
down_revision = 'a4625ffa418d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comments_entered_by_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_entered_by_id_users'), 'users', ['entered_by_id'], ['id'])
        batch_op.drop_column('entered_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comments_entered_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_entered_by_users', 'users', ['entered_by'], ['id'])
        batch_op.drop_column('entered_by_id')

    # ### end Alembic commands ###
